### ISSUE TITLE
  KeyError: 'uniF87A'

### ISSUE THREAD

**Issue by PuHaoran** [Ingram7/maoyan_font#1]
执行python maoyan_font.py（本人python3.6），报错：
Traceback (most recent call last):
  File "maoyan_font.py", line 85, in <module>
    maoyan.start_crawl()
  File "maoyan_font.py", line 76, in start_crawl
    response = self.replace_font(response)
  File "maoyan_font.py", line 51, in replace_font
    response = response.replace(pattern, new_dict[i])
KeyError: 'uniE623'
localhost:maoyan_font hammer$ python maoyan_font.py 
Traceback (most recent call last):
  File "maoyan_font.py", line 85, in <module>
    maoyan.start_crawl()
  File "maoyan_font.py", line 76, in start_crawl
    response = self.replace_font(response)
  File "maoyan_font.py", line 51, in replace_font
    response = response.replace(pattern, new_dict[i])
KeyError: 'uniF87A'

**Comment by suiyingsky** [comment]
这说明两个font对象中的glyf 中没有匹配到一样的数据，数据判断则是通过判断同一个点位数据相差值来确认的，这样有可能导致数据不准确！

**Comment by Ingram7** [comment]
3天前更新了代码，再试试
